/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantsIndexRouteImport } from './routes/assistants.index'
import { Route as AssistantsIdRouteImport } from './routes/assistants.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantsIndexRoute = AssistantsIndexRouteImport.update({
  id: '/assistants/',
  path: '/assistants/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantsIdRoute = AssistantsIdRouteImport.update({
  id: '/assistants/$id',
  path: '/assistants/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistants/$id': typeof AssistantsIdRoute
  '/assistants/': typeof AssistantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistants/$id': typeof AssistantsIdRoute
  '/assistants': typeof AssistantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistants/$id': typeof AssistantsIdRoute
  '/assistants/': typeof AssistantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assistants/$id' | '/assistants/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assistants/$id' | '/assistants'
  id: '__root__' | '/' | '/assistants/$id' | '/assistants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantsIdRoute: typeof AssistantsIdRoute
  AssistantsIndexRoute: typeof AssistantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistants/': {
      id: '/assistants/'
      path: '/assistants'
      fullPath: '/assistants/'
      preLoaderRoute: typeof AssistantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistants/$id': {
      id: '/assistants/$id'
      path: '/assistants/$id'
      fullPath: '/assistants/$id'
      preLoaderRoute: typeof AssistantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantsIdRoute: AssistantsIdRoute,
  AssistantsIndexRoute: AssistantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
