#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# worktree-up.sh  —  Set up an isolated environment for a git worktree.
#
# What it does:
#   1. Assigns a unique port range for this worktree (stored in .worktrees.json).
#   2. Writes .worktree.env at the repo root with all ports/DB names.
#   3. Starts dedicated Postgres containers for dev + E2E (pgvector image).
#   4. Waits for both databases to be ready.
#   5. Runs alembic migrations on both databases.
#   6. Seeds catalog models on both databases.
#
# Idempotent: safe to run again — re-uses existing containers and port
# assignments, and alembic upgrade head is always a no-op if already current.
#
# Usage:
#   ./scripts/worktree-up.sh <worktree-name>
#
# Port scheme (index 0 = main branch, reserved):
#   apiPort          = 8000 + index*2     (dev backend)
#   e2eApiPort       = 8001 + index*2     (E2E backend, used by e2e-up.sh)
#   frontendPort     = 5173 + index*3     (vite dev server)
#   e2eFrontendPort  = 5175 + index*3     (vite E2E server, used by playwright)
#   dbPort           = 5434 + index*2     (dev postgres)
#   e2eDbPort        = 5435 + index*2     (E2E postgres)
# ---------------------------------------------------------------------------
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKTREES_JSON="$REPO_ROOT/.worktrees.json"
WORKTREE_ENV="$REPO_ROOT/.worktree.env"

# ── Argument ─────────────────────────────────────────────────────────────────
NAME="${1:-}"
if [ -z "$NAME" ]; then
  echo "Usage: $0 <worktree-name>" >&2
  exit 1
fi

# Sanitize for use as Postgres DB name (replace - and spaces with _)
SAFE_NAME="${NAME//-/_}"
SAFE_NAME="${SAFE_NAME// /_}"

# ── Resolve Python ────────────────────────────────────────────────────────────
if [ -z "${PYTHON:-}" ]; then
  for _candidate in python python3; do
    if command -v "$_candidate" &>/dev/null && "$_candidate" -c "import alembic" &>/dev/null; then
      PYTHON="$_candidate"
      break
    fi
  done
  : "${PYTHON:?ERROR: could not find Python with alembic. Activate your venv first.}"
fi

# ── Assign or retrieve port slot ─────────────────────────────────────────────
# Initialise .worktrees.json with the main slot pre-reserved if missing.
if [ ! -f "$WORKTREES_JSON" ]; then
  cat > "$WORKTREES_JSON" << 'JSON'
{
  "registry": {
    "main": {
      "index": 0,
      "apiPort": 8000,
      "e2eApiPort": 8001,
      "frontendPort": 5173,
      "e2eFrontendPort": 5175,
      "dbPort": 5434,
      "e2eDbPort": 5435,
      "dbName": "ai_portal",
      "e2eDbName": "ai_portal_e2e"
    }
  }
}
JSON
  echo "▶ Created .worktrees.json (main slot reserved)"
fi

# Python snippet: find/assign index and compute ports, print as space-separated line.
ASSIGNED=$("$PYTHON" - "$WORKTREES_JSON" "$NAME" "$SAFE_NAME" << 'PYEOF'
import json, sys

path, name, safe_name = sys.argv[1], sys.argv[2], sys.argv[3]

with open(path) as f:
    data = json.load(f)

registry = data.setdefault("registry", {})

if name in registry:
    e = registry[name]
    print(e["index"], e["apiPort"], e["e2eApiPort"],
          e["frontendPort"], e["e2eFrontendPort"],
          e["dbPort"], e["e2eDbPort"],
          e["dbName"], e["e2eDbName"])
    sys.exit(0)

used = {v["index"] for v in registry.values()}
idx = 1
while idx in used:
    idx += 1

api      = 8000 + idx * 2
e2e_api  = api + 1
fe       = 5173 + idx * 3
e2e_fe   = fe + 2
db       = 5434 + idx * 2
e2e_db   = db + 1

entry = {
    "index": idx,
    "apiPort": api, "e2eApiPort": e2e_api,
    "frontendPort": fe, "e2eFrontendPort": e2e_fe,
    "dbPort": db, "e2eDbPort": e2e_db,
    "dbName": f"ai_portal_{safe_name}",
    "e2eDbName": f"ai_portal_e2e_{safe_name}",
}
registry[name] = entry
with open(path, "w") as f:
    json.dump(data, f, indent=2)
    f.write("\n")

print(entry["index"], entry["apiPort"], entry["e2eApiPort"],
      entry["frontendPort"], entry["e2eFrontendPort"],
      entry["dbPort"], entry["e2eDbPort"],
      entry["dbName"], entry["e2eDbName"])
PYEOF
)

read -r INDEX API_PORT E2E_API_PORT FRONTEND_PORT E2E_FRONTEND_PORT \
       DB_PORT E2E_DB_PORT DB_NAME E2E_DB_NAME <<< "$ASSIGNED"

echo "▶ Worktree '${NAME}' (slot ${INDEX})"
printf "   dev  — API :%s  frontend :%s  db :%s  (%s)\n" \
  "$API_PORT" "$FRONTEND_PORT" "$DB_PORT" "$DB_NAME"
printf "   e2e  — API :%s  frontend :%s  db :%s  (%s)\n" \
  "$E2E_API_PORT" "$E2E_FRONTEND_PORT" "$E2E_DB_PORT" "$E2E_DB_NAME"

# ── Write .worktree.env ───────────────────────────────────────────────────────
cat > "$WORKTREE_ENV" << EOF
# Generated by scripts/worktree-up.sh — do not edit manually.
# Re-run worktree-up.sh to regenerate.
WORKTREE_NAME=${NAME}
API_PORT=${API_PORT}
E2E_API_PORT=${E2E_API_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
E2E_FRONTEND_PORT=${E2E_FRONTEND_PORT}
DB_PORT=${DB_PORT}
E2E_DB_PORT=${E2E_DB_PORT}
DB_NAME=${DB_NAME}
E2E_DB_NAME=${E2E_DB_NAME}
EOF
echo "▶ Written .worktree.env"

# ── Helper: start a Postgres container ───────────────────────────────────────
start_pg() {
  local cname="$1" port="$2" dbname="$3"

  if docker inspect "$cname" &>/dev/null; then
    local state
    state=$(docker inspect -f '{{.State.Status}}' "$cname")
    if [ "$state" != "running" ]; then
      echo "   $cname exists but is $state — starting..."
      docker start "$cname" > /dev/null
    else
      echo "   $cname already running — skipping create."
    fi
  else
    echo "   Creating $cname on 127.0.0.1:${port}..."
    docker run -d \
      --name "$cname" \
      -e POSTGRES_DB="$dbname" \
      -e POSTGRES_USER=postgres \
      -e POSTGRES_PASSWORD=postgres \
      -p "127.0.0.1:${port}:5432" \
      pgvector/pgvector:pg17 \
      > /dev/null
  fi

  echo -n "   Waiting for $cname..."
  for i in $(seq 1 30); do
    if docker exec "$cname" pg_isready -U postgres -d "$dbname" -q 2>/dev/null; then
      echo " ready (${i}s)."
      return 0
    fi
    if [ "$i" -eq 30 ]; then
      echo ""
      echo "   ERROR: $cname did not become ready in 30s." >&2
      exit 1
    fi
    sleep 1
    echo -n "."
  done
}

# ── 1. Start Postgres containers ──────────────────────────────────────────────
echo "▶ Starting dev Postgres..."
start_pg "local-ai-portal-db-${NAME}" "$DB_PORT" "$DB_NAME"

echo "▶ Starting E2E Postgres..."
start_pg "local-e2e-ai-portal-db-${NAME}" "$E2E_DB_PORT" "$E2E_DB_NAME"

# ── Load .env for API keys ────────────────────────────────────────────────────
if [ -f "$REPO_ROOT/.env" ]; then
  set -o allexport
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env"
  set +o allexport
fi

DEV_DB_URL="postgresql+psycopg://postgres:postgres@127.0.0.1:${DB_PORT}/${DB_NAME}"
E2E_DB_URL="postgresql+psycopg://postgres:postgres@127.0.0.1:${E2E_DB_PORT}/${E2E_DB_NAME}"

# ── 2. Run migrations ─────────────────────────────────────────────────────────
echo "▶ Running alembic migrations (dev DB)..."
(cd "$REPO_ROOT/backend" && DATABASE_URL="$DEV_DB_URL" "$PYTHON" -m alembic upgrade head)

echo "▶ Running alembic migrations (E2E DB)..."
(cd "$REPO_ROOT/backend" && DATABASE_URL="$E2E_DB_URL" "$PYTHON" -m alembic upgrade head)

# ── 3. Seed catalog models ────────────────────────────────────────────────────
echo "▶ Seeding catalog models (dev DB)..."
(cd "$REPO_ROOT/backend" && DATABASE_URL="$DEV_DB_URL" \
  "$PYTHON" -m ai_portal.scripts.seed_catalog_models --skip-model-validation)

echo "▶ Seeding catalog models (E2E DB)..."
(cd "$REPO_ROOT/backend" && DATABASE_URL="$E2E_DB_URL" \
  "$PYTHON" -m ai_portal.scripts.seed_catalog_models --skip-model-validation)

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "✓ Worktree '${NAME}' is ready."
echo ""
echo "  Start dev backend:   source .worktree.env && cd backend && DATABASE_URL=postgresql+psycopg://postgres:postgres@127.0.0.1:\${DB_PORT}/\${DB_NAME} python -m uvicorn ai_portal.main:app --host 127.0.0.1 --port \${API_PORT} --reload"
echo "  Start E2E stack:     ./scripts/e2e-up.sh   (auto-reads .worktree.env)"
echo "  Start frontend:      source .worktree.env && cd frontend && pnpm dev --host"
echo "  Run E2E tests:       cd frontend && pnpm test:e2e"
echo "  Tear down:           ./scripts/worktree-down.sh ${NAME}"
