/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkersRouteRouteImport } from './routes/workers/route'
import { Route as RagRouteRouteImport } from './routes/rag/route'
import { Route as GatewayRouteRouteImport } from './routes/gateway/route'
import { Route as ChatRouteRouteImport } from './routes/chat/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers/index'
import { Route as KnowledgeBasesIndexRouteImport } from './routes/knowledge-bases/index'
import { Route as GatewayIndexRouteImport } from './routes/gateway/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WorkersTasksRouteImport } from './routes/workers/tasks'
import { Route as WorkersSettingsRouteImport } from './routes/workers/settings'
import { Route as WorkersPoolsRouteImport } from './routes/workers/pools'
import { Route as WorkersIntegrationsRouteImport } from './routes/workers/integrations'
import { Route as WorkersInstancesRouteImport } from './routes/workers/instances'
import { Route as WorkersAnalyticsRouteImport } from './routes/workers/analytics'
import { Route as RagSearchProvidersRouteImport } from './routes/rag/search-providers'
import { Route as RagMarketplaceRouteImport } from './routes/rag/marketplace'
import { Route as OrgSettingsRouteImport } from './routes/org/settings'
import { Route as OrgConsumptionRouteImport } from './routes/org/consumption'
import { Route as MemoriesSharedRouteImport } from './routes/memories/shared'
import { Route as MemoriesSettingsRouteImport } from './routes/memories/settings'
import { Route as MemoriesMyRouteImport } from './routes/memories/my'
import { Route as KnowledgeBasesIdRouteImport } from './routes/knowledge-bases/$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as GatewayTracesRouteImport } from './routes/gateway/traces'
import { Route as GatewaySnippetsRouteImport } from './routes/gateway/snippets'
import { Route as GatewayRoutingRouteImport } from './routes/gateway/routing'
import { Route as GatewayProvidersRouteImport } from './routes/gateway/providers'
import { Route as GatewayPlaygroundRouteImport } from './routes/gateway/playground'
import { Route as GatewayOverviewRouteImport } from './routes/gateway/overview'
import { Route as GatewayModelsRouteImport } from './routes/gateway/models'
import { Route as GatewayGuardrailsRouteImport } from './routes/gateway/guardrails'
import { Route as GatewayEvalsRouteImport } from './routes/gateway/evals'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminWebhooksRouteImport } from './routes/admin/webhooks'
import { Route as AdminUsageRouteImport } from './routes/admin/usage'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminSsoRouteImport } from './routes/admin/sso'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminScimRouteImport } from './routes/admin/scim'
import { Route as AdminMemoryPoliciesRouteImport } from './routes/admin/memory-policies'
import { Route as AdminMemoryAnalyticsRouteImport } from './routes/admin/memory-analytics'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminDirectoryRouteImport } from './routes/admin/directory'
import { Route as AdminDataRouteImport } from './routes/admin/data'
import { Route as AdminBudgetsRouteImport } from './routes/admin/budgets'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminApiKeysRouteImport } from './routes/admin/api-keys'
import { Route as ChatConversationsRouteRouteImport } from './routes/chat/conversations/route'
import { Route as RagKbsIndexRouteImport } from './routes/rag/kbs.index'
import { Route as ChatConversationsIndexRouteImport } from './routes/chat/conversations/index'
import { Route as WorkersTasksTaskIdRouteImport } from './routes/workers/tasks.$taskId'
import { Route as WorkersInstancesWorkerIdRouteImport } from './routes/workers/instances.$workerId'
import { Route as ChatConversationsIdRouteImport } from './routes/chat/conversations/$id'
import { Route as WorkersPoolsIdTemplateRouteImport } from './routes/workers/pools.$id.template'
import { Route as RagKbsIdSettingsRouteImport } from './routes/rag/kbs.$id.settings'
import { Route as RagKbsIdQuarantineRouteImport } from './routes/rag/kbs.$id.quarantine'
import { Route as RagKbsIdPlaygroundRouteImport } from './routes/rag/kbs.$id.playground'
import { Route as RagKbsIdPermissionsRouteImport } from './routes/rag/kbs.$id.permissions'
import { Route as RagKbsIdOverviewRouteImport } from './routes/rag/kbs.$id.overview'
import { Route as RagKbsIdEvalsRouteImport } from './routes/rag/kbs.$id.evals'
import { Route as RagKbsIdDocumentsRouteImport } from './routes/rag/kbs.$id.documents'
import { Route as RagKbsIdConnectorsRouteImport } from './routes/rag/kbs.$id.connectors'
import { Route as RagKbsIdAnalyticsRouteImport } from './routes/rag/kbs.$id.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRouteRoute = WorkersRouteRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const RagRouteRoute = RagRouteRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayRouteRoute = GatewayRouteRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkersRouteRoute,
} as any)
const KnowledgeBasesIndexRoute = KnowledgeBasesIndexRouteImport.update({
  id: '/knowledge-bases/',
  path: '/knowledge-bases/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayIndexRoute = GatewayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GatewayRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WorkersTasksRoute = WorkersTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => WorkersRouteRoute,
} as any)
const WorkersSettingsRoute = WorkersSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkersRouteRoute,
} as any)
const WorkersPoolsRoute = WorkersPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => WorkersRouteRoute,
} as any)
const WorkersIntegrationsRoute = WorkersIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => WorkersRouteRoute,
} as any)
const WorkersInstancesRoute = WorkersInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => WorkersRouteRoute,
} as any)
const WorkersAnalyticsRoute = WorkersAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WorkersRouteRoute,
} as any)
const RagSearchProvidersRoute = RagSearchProvidersRouteImport.update({
  id: '/search-providers',
  path: '/search-providers',
  getParentRoute: () => RagRouteRoute,
} as any)
const RagMarketplaceRoute = RagMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => RagRouteRoute,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/org/settings',
  path: '/org/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgConsumptionRoute = OrgConsumptionRouteImport.update({
  id: '/org/consumption',
  path: '/org/consumption',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesSharedRoute = MemoriesSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => MemoriesRoute,
} as any)
const MemoriesSettingsRoute = MemoriesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MemoriesRoute,
} as any)
const MemoriesMyRoute = MemoriesMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => MemoriesRoute,
} as any)
const KnowledgeBasesIdRoute = KnowledgeBasesIdRouteImport.update({
  id: '/knowledge-bases/$id',
  path: '/knowledge-bases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GatewayTracesRoute = GatewayTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => GatewayRouteRoute,
} as any)
const GatewaySnippetsRoute = GatewaySnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => GatewayRouteRoute,
} as any)
const GatewayRoutingRoute = GatewayRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => GatewayRouteRoute,
} as any)
const GatewayProvidersRoute = GatewayProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => GatewayRouteRoute,
} as any)
const GatewayPlaygroundRoute = GatewayPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => GatewayRouteRoute,
} as any)
const GatewayOverviewRoute = GatewayOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => GatewayRouteRoute,
} as any)
const GatewayModelsRoute = GatewayModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => GatewayRouteRoute,
} as any)
const GatewayGuardrailsRoute = GatewayGuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => GatewayRouteRoute,
} as any)
const GatewayEvalsRoute = GatewayEvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => GatewayRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSsoRoute = AdminSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScimRoute = AdminScimRouteImport.update({
  id: '/scim',
  path: '/scim',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMemoryPoliciesRoute = AdminMemoryPoliciesRouteImport.update({
  id: '/memory-policies',
  path: '/memory-policies',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMemoryAnalyticsRoute = AdminMemoryAnalyticsRouteImport.update({
  id: '/memory-analytics',
  path: '/memory-analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBudgetsRoute = AdminBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ChatConversationsRouteRoute = ChatConversationsRouteRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => ChatRouteRoute,
} as any)
const RagKbsIndexRoute = RagKbsIndexRouteImport.update({
  id: '/kbs/',
  path: '/kbs/',
  getParentRoute: () => RagRouteRoute,
} as any)
const ChatConversationsIndexRoute = ChatConversationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatConversationsRouteRoute,
} as any)
const WorkersTasksTaskIdRoute = WorkersTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => WorkersTasksRoute,
} as any)
const WorkersInstancesWorkerIdRoute =
  WorkersInstancesWorkerIdRouteImport.update({
    id: '/$workerId',
    path: '/$workerId',
    getParentRoute: () => WorkersInstancesRoute,
  } as any)
const ChatConversationsIdRoute = ChatConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatConversationsRouteRoute,
} as any)
const WorkersPoolsIdTemplateRoute = WorkersPoolsIdTemplateRouteImport.update({
  id: '/$id/template',
  path: '/$id/template',
  getParentRoute: () => WorkersPoolsRoute,
} as any)
const RagKbsIdSettingsRoute = RagKbsIdSettingsRouteImport.update({
  id: '/kbs/$id/settings',
  path: '/kbs/$id/settings',
  getParentRoute: () => RagRouteRoute,
} as any)
const RagKbsIdQuarantineRoute = RagKbsIdQuarantineRouteImport.update({
  id: '/kbs/$id/quarantine',
  path: '/kbs/$id/quarantine',
  getParentRoute: () => RagRouteRoute,
} as any)
const RagKbsIdPlaygroundRoute = RagKbsIdPlaygroundRouteImport.update({
  id: '/kbs/$id/playground',
  path: '/kbs/$id/playground',
  getParentRoute: () => RagRouteRoute,
} as any)
const RagKbsIdPermissionsRoute = RagKbsIdPermissionsRouteImport.update({
  id: '/kbs/$id/permissions',
  path: '/kbs/$id/permissions',
  getParentRoute: () => RagRouteRoute,
} as any)
const RagKbsIdOverviewRoute = RagKbsIdOverviewRouteImport.update({
  id: '/kbs/$id/overview',
  path: '/kbs/$id/overview',
  getParentRoute: () => RagRouteRoute,
} as any)
const RagKbsIdEvalsRoute = RagKbsIdEvalsRouteImport.update({
  id: '/kbs/$id/evals',
  path: '/kbs/$id/evals',
  getParentRoute: () => RagRouteRoute,
} as any)
const RagKbsIdDocumentsRoute = RagKbsIdDocumentsRouteImport.update({
  id: '/kbs/$id/documents',
  path: '/kbs/$id/documents',
  getParentRoute: () => RagRouteRoute,
} as any)
const RagKbsIdConnectorsRoute = RagKbsIdConnectorsRouteImport.update({
  id: '/kbs/$id/connectors',
  path: '/kbs/$id/connectors',
  getParentRoute: () => RagRouteRoute,
} as any)
const RagKbsIdAnalyticsRoute = RagKbsIdAnalyticsRouteImport.update({
  id: '/kbs/$id/analytics',
  path: '/kbs/$id/analytics',
  getParentRoute: () => RagRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/chat': typeof ChatRouteRouteWithChildren
  '/gateway': typeof GatewayRouteRouteWithChildren
  '/rag': typeof RagRouteRouteWithChildren
  '/workers': typeof WorkersRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/register': typeof RegisterRoute
  '/chat/conversations': typeof ChatConversationsRouteRouteWithChildren
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/budgets': typeof AdminBudgetsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memory-analytics': typeof AdminMemoryAnalyticsRoute
  '/admin/memory-policies': typeof AdminMemoryPoliciesRoute
  '/admin/scim': typeof AdminScimRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sso': typeof AdminSsoRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gateway/evals': typeof GatewayEvalsRoute
  '/gateway/guardrails': typeof GatewayGuardrailsRoute
  '/gateway/models': typeof GatewayModelsRoute
  '/gateway/overview': typeof GatewayOverviewRoute
  '/gateway/playground': typeof GatewayPlaygroundRoute
  '/gateway/providers': typeof GatewayProvidersRoute
  '/gateway/routing': typeof GatewayRoutingRoute
  '/gateway/snippets': typeof GatewaySnippetsRoute
  '/gateway/traces': typeof GatewayTracesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
  '/memories/my': typeof MemoriesMyRoute
  '/memories/settings': typeof MemoriesSettingsRoute
  '/memories/shared': typeof MemoriesSharedRoute
  '/org/consumption': typeof OrgConsumptionRoute
  '/org/settings': typeof OrgSettingsRoute
  '/rag/marketplace': typeof RagMarketplaceRoute
  '/rag/search-providers': typeof RagSearchProvidersRoute
  '/workers/analytics': typeof WorkersAnalyticsRoute
  '/workers/instances': typeof WorkersInstancesRouteWithChildren
  '/workers/integrations': typeof WorkersIntegrationsRoute
  '/workers/pools': typeof WorkersPoolsRouteWithChildren
  '/workers/settings': typeof WorkersSettingsRoute
  '/workers/tasks': typeof WorkersTasksRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/gateway/': typeof GatewayIndexRoute
  '/knowledge-bases/': typeof KnowledgeBasesIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/chat/conversations/$id': typeof ChatConversationsIdRoute
  '/workers/instances/$workerId': typeof WorkersInstancesWorkerIdRoute
  '/workers/tasks/$taskId': typeof WorkersTasksTaskIdRoute
  '/chat/conversations/': typeof ChatConversationsIndexRoute
  '/rag/kbs/': typeof RagKbsIndexRoute
  '/rag/kbs/$id/analytics': typeof RagKbsIdAnalyticsRoute
  '/rag/kbs/$id/connectors': typeof RagKbsIdConnectorsRoute
  '/rag/kbs/$id/documents': typeof RagKbsIdDocumentsRoute
  '/rag/kbs/$id/evals': typeof RagKbsIdEvalsRoute
  '/rag/kbs/$id/overview': typeof RagKbsIdOverviewRoute
  '/rag/kbs/$id/permissions': typeof RagKbsIdPermissionsRoute
  '/rag/kbs/$id/playground': typeof RagKbsIdPlaygroundRoute
  '/rag/kbs/$id/quarantine': typeof RagKbsIdQuarantineRoute
  '/rag/kbs/$id/settings': typeof RagKbsIdSettingsRoute
  '/workers/pools/$id/template': typeof WorkersPoolsIdTemplateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/rag': typeof RagRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/budgets': typeof AdminBudgetsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memory-analytics': typeof AdminMemoryAnalyticsRoute
  '/admin/memory-policies': typeof AdminMemoryPoliciesRoute
  '/admin/scim': typeof AdminScimRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sso': typeof AdminSsoRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gateway/evals': typeof GatewayEvalsRoute
  '/gateway/guardrails': typeof GatewayGuardrailsRoute
  '/gateway/models': typeof GatewayModelsRoute
  '/gateway/overview': typeof GatewayOverviewRoute
  '/gateway/playground': typeof GatewayPlaygroundRoute
  '/gateway/providers': typeof GatewayProvidersRoute
  '/gateway/routing': typeof GatewayRoutingRoute
  '/gateway/snippets': typeof GatewaySnippetsRoute
  '/gateway/traces': typeof GatewayTracesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
  '/memories/my': typeof MemoriesMyRoute
  '/memories/settings': typeof MemoriesSettingsRoute
  '/memories/shared': typeof MemoriesSharedRoute
  '/org/consumption': typeof OrgConsumptionRoute
  '/org/settings': typeof OrgSettingsRoute
  '/rag/marketplace': typeof RagMarketplaceRoute
  '/rag/search-providers': typeof RagSearchProvidersRoute
  '/workers/analytics': typeof WorkersAnalyticsRoute
  '/workers/instances': typeof WorkersInstancesRouteWithChildren
  '/workers/integrations': typeof WorkersIntegrationsRoute
  '/workers/pools': typeof WorkersPoolsRouteWithChildren
  '/workers/settings': typeof WorkersSettingsRoute
  '/workers/tasks': typeof WorkersTasksRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/gateway': typeof GatewayIndexRoute
  '/knowledge-bases': typeof KnowledgeBasesIndexRoute
  '/workers': typeof WorkersIndexRoute
  '/chat/conversations/$id': typeof ChatConversationsIdRoute
  '/workers/instances/$workerId': typeof WorkersInstancesWorkerIdRoute
  '/workers/tasks/$taskId': typeof WorkersTasksTaskIdRoute
  '/chat/conversations': typeof ChatConversationsIndexRoute
  '/rag/kbs': typeof RagKbsIndexRoute
  '/rag/kbs/$id/analytics': typeof RagKbsIdAnalyticsRoute
  '/rag/kbs/$id/connectors': typeof RagKbsIdConnectorsRoute
  '/rag/kbs/$id/documents': typeof RagKbsIdDocumentsRoute
  '/rag/kbs/$id/evals': typeof RagKbsIdEvalsRoute
  '/rag/kbs/$id/overview': typeof RagKbsIdOverviewRoute
  '/rag/kbs/$id/permissions': typeof RagKbsIdPermissionsRoute
  '/rag/kbs/$id/playground': typeof RagKbsIdPlaygroundRoute
  '/rag/kbs/$id/quarantine': typeof RagKbsIdQuarantineRoute
  '/rag/kbs/$id/settings': typeof RagKbsIdSettingsRoute
  '/workers/pools/$id/template': typeof WorkersPoolsIdTemplateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/chat': typeof ChatRouteRouteWithChildren
  '/gateway': typeof GatewayRouteRouteWithChildren
  '/rag': typeof RagRouteRouteWithChildren
  '/workers': typeof WorkersRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/register': typeof RegisterRoute
  '/chat/conversations': typeof ChatConversationsRouteRouteWithChildren
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/budgets': typeof AdminBudgetsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/memory-analytics': typeof AdminMemoryAnalyticsRoute
  '/admin/memory-policies': typeof AdminMemoryPoliciesRoute
  '/admin/scim': typeof AdminScimRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sso': typeof AdminSsoRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gateway/evals': typeof GatewayEvalsRoute
  '/gateway/guardrails': typeof GatewayGuardrailsRoute
  '/gateway/models': typeof GatewayModelsRoute
  '/gateway/overview': typeof GatewayOverviewRoute
  '/gateway/playground': typeof GatewayPlaygroundRoute
  '/gateway/providers': typeof GatewayProvidersRoute
  '/gateway/routing': typeof GatewayRoutingRoute
  '/gateway/snippets': typeof GatewaySnippetsRoute
  '/gateway/traces': typeof GatewayTracesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
  '/memories/my': typeof MemoriesMyRoute
  '/memories/settings': typeof MemoriesSettingsRoute
  '/memories/shared': typeof MemoriesSharedRoute
  '/org/consumption': typeof OrgConsumptionRoute
  '/org/settings': typeof OrgSettingsRoute
  '/rag/marketplace': typeof RagMarketplaceRoute
  '/rag/search-providers': typeof RagSearchProvidersRoute
  '/workers/analytics': typeof WorkersAnalyticsRoute
  '/workers/instances': typeof WorkersInstancesRouteWithChildren
  '/workers/integrations': typeof WorkersIntegrationsRoute
  '/workers/pools': typeof WorkersPoolsRouteWithChildren
  '/workers/settings': typeof WorkersSettingsRoute
  '/workers/tasks': typeof WorkersTasksRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/gateway/': typeof GatewayIndexRoute
  '/knowledge-bases/': typeof KnowledgeBasesIndexRoute
  '/workers/': typeof WorkersIndexRoute
  '/chat/conversations/$id': typeof ChatConversationsIdRoute
  '/workers/instances/$workerId': typeof WorkersInstancesWorkerIdRoute
  '/workers/tasks/$taskId': typeof WorkersTasksTaskIdRoute
  '/chat/conversations/': typeof ChatConversationsIndexRoute
  '/rag/kbs/': typeof RagKbsIndexRoute
  '/rag/kbs/$id/analytics': typeof RagKbsIdAnalyticsRoute
  '/rag/kbs/$id/connectors': typeof RagKbsIdConnectorsRoute
  '/rag/kbs/$id/documents': typeof RagKbsIdDocumentsRoute
  '/rag/kbs/$id/evals': typeof RagKbsIdEvalsRoute
  '/rag/kbs/$id/overview': typeof RagKbsIdOverviewRoute
  '/rag/kbs/$id/permissions': typeof RagKbsIdPermissionsRoute
  '/rag/kbs/$id/playground': typeof RagKbsIdPlaygroundRoute
  '/rag/kbs/$id/quarantine': typeof RagKbsIdQuarantineRoute
  '/rag/kbs/$id/settings': typeof RagKbsIdSettingsRoute
  '/workers/pools/$id/template': typeof WorkersPoolsIdTemplateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/gateway'
    | '/rag'
    | '/workers'
    | '/login'
    | '/memories'
    | '/register'
    | '/chat/conversations'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/budgets'
    | '/admin/data'
    | '/admin/directory'
    | '/admin/members'
    | '/admin/memory-analytics'
    | '/admin/memory-policies'
    | '/admin/scim'
    | '/admin/settings'
    | '/admin/sso'
    | '/admin/teams'
    | '/admin/usage'
    | '/admin/webhooks'
    | '/auth/callback'
    | '/gateway/evals'
    | '/gateway/guardrails'
    | '/gateway/models'
    | '/gateway/overview'
    | '/gateway/playground'
    | '/gateway/providers'
    | '/gateway/routing'
    | '/gateway/snippets'
    | '/gateway/traces'
    | '/invite/$token'
    | '/knowledge-bases/$id'
    | '/memories/my'
    | '/memories/settings'
    | '/memories/shared'
    | '/org/consumption'
    | '/org/settings'
    | '/rag/marketplace'
    | '/rag/search-providers'
    | '/workers/analytics'
    | '/workers/instances'
    | '/workers/integrations'
    | '/workers/pools'
    | '/workers/settings'
    | '/workers/tasks'
    | '/admin/'
    | '/gateway/'
    | '/knowledge-bases/'
    | '/workers/'
    | '/chat/conversations/$id'
    | '/workers/instances/$workerId'
    | '/workers/tasks/$taskId'
    | '/chat/conversations/'
    | '/rag/kbs/'
    | '/rag/kbs/$id/analytics'
    | '/rag/kbs/$id/connectors'
    | '/rag/kbs/$id/documents'
    | '/rag/kbs/$id/evals'
    | '/rag/kbs/$id/overview'
    | '/rag/kbs/$id/permissions'
    | '/rag/kbs/$id/playground'
    | '/rag/kbs/$id/quarantine'
    | '/rag/kbs/$id/settings'
    | '/workers/pools/$id/template'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/rag'
    | '/login'
    | '/memories'
    | '/register'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/budgets'
    | '/admin/data'
    | '/admin/directory'
    | '/admin/members'
    | '/admin/memory-analytics'
    | '/admin/memory-policies'
    | '/admin/scim'
    | '/admin/settings'
    | '/admin/sso'
    | '/admin/teams'
    | '/admin/usage'
    | '/admin/webhooks'
    | '/auth/callback'
    | '/gateway/evals'
    | '/gateway/guardrails'
    | '/gateway/models'
    | '/gateway/overview'
    | '/gateway/playground'
    | '/gateway/providers'
    | '/gateway/routing'
    | '/gateway/snippets'
    | '/gateway/traces'
    | '/invite/$token'
    | '/knowledge-bases/$id'
    | '/memories/my'
    | '/memories/settings'
    | '/memories/shared'
    | '/org/consumption'
    | '/org/settings'
    | '/rag/marketplace'
    | '/rag/search-providers'
    | '/workers/analytics'
    | '/workers/instances'
    | '/workers/integrations'
    | '/workers/pools'
    | '/workers/settings'
    | '/workers/tasks'
    | '/admin'
    | '/gateway'
    | '/knowledge-bases'
    | '/workers'
    | '/chat/conversations/$id'
    | '/workers/instances/$workerId'
    | '/workers/tasks/$taskId'
    | '/chat/conversations'
    | '/rag/kbs'
    | '/rag/kbs/$id/analytics'
    | '/rag/kbs/$id/connectors'
    | '/rag/kbs/$id/documents'
    | '/rag/kbs/$id/evals'
    | '/rag/kbs/$id/overview'
    | '/rag/kbs/$id/permissions'
    | '/rag/kbs/$id/playground'
    | '/rag/kbs/$id/quarantine'
    | '/rag/kbs/$id/settings'
    | '/workers/pools/$id/template'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/gateway'
    | '/rag'
    | '/workers'
    | '/login'
    | '/memories'
    | '/register'
    | '/chat/conversations'
    | '/admin/api-keys'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/budgets'
    | '/admin/data'
    | '/admin/directory'
    | '/admin/members'
    | '/admin/memory-analytics'
    | '/admin/memory-policies'
    | '/admin/scim'
    | '/admin/settings'
    | '/admin/sso'
    | '/admin/teams'
    | '/admin/usage'
    | '/admin/webhooks'
    | '/auth/callback'
    | '/gateway/evals'
    | '/gateway/guardrails'
    | '/gateway/models'
    | '/gateway/overview'
    | '/gateway/playground'
    | '/gateway/providers'
    | '/gateway/routing'
    | '/gateway/snippets'
    | '/gateway/traces'
    | '/invite/$token'
    | '/knowledge-bases/$id'
    | '/memories/my'
    | '/memories/settings'
    | '/memories/shared'
    | '/org/consumption'
    | '/org/settings'
    | '/rag/marketplace'
    | '/rag/search-providers'
    | '/workers/analytics'
    | '/workers/instances'
    | '/workers/integrations'
    | '/workers/pools'
    | '/workers/settings'
    | '/workers/tasks'
    | '/admin/'
    | '/gateway/'
    | '/knowledge-bases/'
    | '/workers/'
    | '/chat/conversations/$id'
    | '/workers/instances/$workerId'
    | '/workers/tasks/$taskId'
    | '/chat/conversations/'
    | '/rag/kbs/'
    | '/rag/kbs/$id/analytics'
    | '/rag/kbs/$id/connectors'
    | '/rag/kbs/$id/documents'
    | '/rag/kbs/$id/evals'
    | '/rag/kbs/$id/overview'
    | '/rag/kbs/$id/permissions'
    | '/rag/kbs/$id/playground'
    | '/rag/kbs/$id/quarantine'
    | '/rag/kbs/$id/settings'
    | '/workers/pools/$id/template'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  GatewayRouteRoute: typeof GatewayRouteRouteWithChildren
  RagRouteRoute: typeof RagRouteRouteWithChildren
  WorkersRouteRoute: typeof WorkersRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  MemoriesRoute: typeof MemoriesRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
  KnowledgeBasesIdRoute: typeof KnowledgeBasesIdRoute
  OrgConsumptionRoute: typeof OrgConsumptionRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  KnowledgeBasesIndexRoute: typeof KnowledgeBasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rag': {
      id: '/rag'
      path: '/rag'
      fullPath: '/rag'
      preLoaderRoute: typeof RagRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway': {
      id: '/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof GatewayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof WorkersRouteRoute
    }
    '/knowledge-bases/': {
      id: '/knowledge-bases/'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases/'
      preLoaderRoute: typeof KnowledgeBasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway/': {
      id: '/gateway/'
      path: '/'
      fullPath: '/gateway/'
      preLoaderRoute: typeof GatewayIndexRouteImport
      parentRoute: typeof GatewayRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/workers/tasks': {
      id: '/workers/tasks'
      path: '/tasks'
      fullPath: '/workers/tasks'
      preLoaderRoute: typeof WorkersTasksRouteImport
      parentRoute: typeof WorkersRouteRoute
    }
    '/workers/settings': {
      id: '/workers/settings'
      path: '/settings'
      fullPath: '/workers/settings'
      preLoaderRoute: typeof WorkersSettingsRouteImport
      parentRoute: typeof WorkersRouteRoute
    }
    '/workers/pools': {
      id: '/workers/pools'
      path: '/pools'
      fullPath: '/workers/pools'
      preLoaderRoute: typeof WorkersPoolsRouteImport
      parentRoute: typeof WorkersRouteRoute
    }
    '/workers/integrations': {
      id: '/workers/integrations'
      path: '/integrations'
      fullPath: '/workers/integrations'
      preLoaderRoute: typeof WorkersIntegrationsRouteImport
      parentRoute: typeof WorkersRouteRoute
    }
    '/workers/instances': {
      id: '/workers/instances'
      path: '/instances'
      fullPath: '/workers/instances'
      preLoaderRoute: typeof WorkersInstancesRouteImport
      parentRoute: typeof WorkersRouteRoute
    }
    '/workers/analytics': {
      id: '/workers/analytics'
      path: '/analytics'
      fullPath: '/workers/analytics'
      preLoaderRoute: typeof WorkersAnalyticsRouteImport
      parentRoute: typeof WorkersRouteRoute
    }
    '/rag/search-providers': {
      id: '/rag/search-providers'
      path: '/search-providers'
      fullPath: '/rag/search-providers'
      preLoaderRoute: typeof RagSearchProvidersRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/rag/marketplace': {
      id: '/rag/marketplace'
      path: '/marketplace'
      fullPath: '/rag/marketplace'
      preLoaderRoute: typeof RagMarketplaceRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/org/settings': {
      id: '/org/settings'
      path: '/org/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/consumption': {
      id: '/org/consumption'
      path: '/org/consumption'
      fullPath: '/org/consumption'
      preLoaderRoute: typeof OrgConsumptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/shared': {
      id: '/memories/shared'
      path: '/shared'
      fullPath: '/memories/shared'
      preLoaderRoute: typeof MemoriesSharedRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/memories/settings': {
      id: '/memories/settings'
      path: '/settings'
      fullPath: '/memories/settings'
      preLoaderRoute: typeof MemoriesSettingsRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/memories/my': {
      id: '/memories/my'
      path: '/my'
      fullPath: '/memories/my'
      preLoaderRoute: typeof MemoriesMyRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/knowledge-bases/$id': {
      id: '/knowledge-bases/$id'
      path: '/knowledge-bases/$id'
      fullPath: '/knowledge-bases/$id'
      preLoaderRoute: typeof KnowledgeBasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gateway/traces': {
      id: '/gateway/traces'
      path: '/traces'
      fullPath: '/gateway/traces'
      preLoaderRoute: typeof GatewayTracesRouteImport
      parentRoute: typeof GatewayRouteRoute
    }
    '/gateway/snippets': {
      id: '/gateway/snippets'
      path: '/snippets'
      fullPath: '/gateway/snippets'
      preLoaderRoute: typeof GatewaySnippetsRouteImport
      parentRoute: typeof GatewayRouteRoute
    }
    '/gateway/routing': {
      id: '/gateway/routing'
      path: '/routing'
      fullPath: '/gateway/routing'
      preLoaderRoute: typeof GatewayRoutingRouteImport
      parentRoute: typeof GatewayRouteRoute
    }
    '/gateway/providers': {
      id: '/gateway/providers'
      path: '/providers'
      fullPath: '/gateway/providers'
      preLoaderRoute: typeof GatewayProvidersRouteImport
      parentRoute: typeof GatewayRouteRoute
    }
    '/gateway/playground': {
      id: '/gateway/playground'
      path: '/playground'
      fullPath: '/gateway/playground'
      preLoaderRoute: typeof GatewayPlaygroundRouteImport
      parentRoute: typeof GatewayRouteRoute
    }
    '/gateway/overview': {
      id: '/gateway/overview'
      path: '/overview'
      fullPath: '/gateway/overview'
      preLoaderRoute: typeof GatewayOverviewRouteImport
      parentRoute: typeof GatewayRouteRoute
    }
    '/gateway/models': {
      id: '/gateway/models'
      path: '/models'
      fullPath: '/gateway/models'
      preLoaderRoute: typeof GatewayModelsRouteImport
      parentRoute: typeof GatewayRouteRoute
    }
    '/gateway/guardrails': {
      id: '/gateway/guardrails'
      path: '/guardrails'
      fullPath: '/gateway/guardrails'
      preLoaderRoute: typeof GatewayGuardrailsRouteImport
      parentRoute: typeof GatewayRouteRoute
    }
    '/gateway/evals': {
      id: '/gateway/evals'
      path: '/evals'
      fullPath: '/gateway/evals'
      preLoaderRoute: typeof GatewayEvalsRouteImport
      parentRoute: typeof GatewayRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sso': {
      id: '/admin/sso'
      path: '/sso'
      fullPath: '/admin/sso'
      preLoaderRoute: typeof AdminSsoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scim': {
      id: '/admin/scim'
      path: '/scim'
      fullPath: '/admin/scim'
      preLoaderRoute: typeof AdminScimRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/memory-policies': {
      id: '/admin/memory-policies'
      path: '/memory-policies'
      fullPath: '/admin/memory-policies'
      preLoaderRoute: typeof AdminMemoryPoliciesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/memory-analytics': {
      id: '/admin/memory-analytics'
      path: '/memory-analytics'
      fullPath: '/admin/memory-analytics'
      preLoaderRoute: typeof AdminMemoryAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/directory': {
      id: '/admin/directory'
      path: '/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/budgets': {
      id: '/admin/budgets'
      path: '/budgets'
      fullPath: '/admin/budgets'
      preLoaderRoute: typeof AdminBudgetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/chat/conversations': {
      id: '/chat/conversations'
      path: '/conversations'
      fullPath: '/chat/conversations'
      preLoaderRoute: typeof ChatConversationsRouteRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/rag/kbs/': {
      id: '/rag/kbs/'
      path: '/kbs'
      fullPath: '/rag/kbs/'
      preLoaderRoute: typeof RagKbsIndexRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/chat/conversations/': {
      id: '/chat/conversations/'
      path: '/'
      fullPath: '/chat/conversations/'
      preLoaderRoute: typeof ChatConversationsIndexRouteImport
      parentRoute: typeof ChatConversationsRouteRoute
    }
    '/workers/tasks/$taskId': {
      id: '/workers/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/workers/tasks/$taskId'
      preLoaderRoute: typeof WorkersTasksTaskIdRouteImport
      parentRoute: typeof WorkersTasksRoute
    }
    '/workers/instances/$workerId': {
      id: '/workers/instances/$workerId'
      path: '/$workerId'
      fullPath: '/workers/instances/$workerId'
      preLoaderRoute: typeof WorkersInstancesWorkerIdRouteImport
      parentRoute: typeof WorkersInstancesRoute
    }
    '/chat/conversations/$id': {
      id: '/chat/conversations/$id'
      path: '/$id'
      fullPath: '/chat/conversations/$id'
      preLoaderRoute: typeof ChatConversationsIdRouteImport
      parentRoute: typeof ChatConversationsRouteRoute
    }
    '/workers/pools/$id/template': {
      id: '/workers/pools/$id/template'
      path: '/$id/template'
      fullPath: '/workers/pools/$id/template'
      preLoaderRoute: typeof WorkersPoolsIdTemplateRouteImport
      parentRoute: typeof WorkersPoolsRoute
    }
    '/rag/kbs/$id/settings': {
      id: '/rag/kbs/$id/settings'
      path: '/kbs/$id/settings'
      fullPath: '/rag/kbs/$id/settings'
      preLoaderRoute: typeof RagKbsIdSettingsRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/rag/kbs/$id/quarantine': {
      id: '/rag/kbs/$id/quarantine'
      path: '/kbs/$id/quarantine'
      fullPath: '/rag/kbs/$id/quarantine'
      preLoaderRoute: typeof RagKbsIdQuarantineRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/rag/kbs/$id/playground': {
      id: '/rag/kbs/$id/playground'
      path: '/kbs/$id/playground'
      fullPath: '/rag/kbs/$id/playground'
      preLoaderRoute: typeof RagKbsIdPlaygroundRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/rag/kbs/$id/permissions': {
      id: '/rag/kbs/$id/permissions'
      path: '/kbs/$id/permissions'
      fullPath: '/rag/kbs/$id/permissions'
      preLoaderRoute: typeof RagKbsIdPermissionsRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/rag/kbs/$id/overview': {
      id: '/rag/kbs/$id/overview'
      path: '/kbs/$id/overview'
      fullPath: '/rag/kbs/$id/overview'
      preLoaderRoute: typeof RagKbsIdOverviewRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/rag/kbs/$id/evals': {
      id: '/rag/kbs/$id/evals'
      path: '/kbs/$id/evals'
      fullPath: '/rag/kbs/$id/evals'
      preLoaderRoute: typeof RagKbsIdEvalsRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/rag/kbs/$id/documents': {
      id: '/rag/kbs/$id/documents'
      path: '/kbs/$id/documents'
      fullPath: '/rag/kbs/$id/documents'
      preLoaderRoute: typeof RagKbsIdDocumentsRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/rag/kbs/$id/connectors': {
      id: '/rag/kbs/$id/connectors'
      path: '/kbs/$id/connectors'
      fullPath: '/rag/kbs/$id/connectors'
      preLoaderRoute: typeof RagKbsIdConnectorsRouteImport
      parentRoute: typeof RagRouteRoute
    }
    '/rag/kbs/$id/analytics': {
      id: '/rag/kbs/$id/analytics'
      path: '/kbs/$id/analytics'
      fullPath: '/rag/kbs/$id/analytics'
      preLoaderRoute: typeof RagKbsIdAnalyticsRouteImport
      parentRoute: typeof RagRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminBudgetsRoute: typeof AdminBudgetsRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMemoryAnalyticsRoute: typeof AdminMemoryAnalyticsRoute
  AdminMemoryPoliciesRoute: typeof AdminMemoryPoliciesRoute
  AdminScimRoute: typeof AdminScimRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSsoRoute: typeof AdminSsoRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminBudgetsRoute: AdminBudgetsRoute,
  AdminDataRoute: AdminDataRoute,
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMemoryAnalyticsRoute: AdminMemoryAnalyticsRoute,
  AdminMemoryPoliciesRoute: AdminMemoryPoliciesRoute,
  AdminScimRoute: AdminScimRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSsoRoute: AdminSsoRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ChatConversationsRouteRouteChildren {
  ChatConversationsIdRoute: typeof ChatConversationsIdRoute
  ChatConversationsIndexRoute: typeof ChatConversationsIndexRoute
}

const ChatConversationsRouteRouteChildren: ChatConversationsRouteRouteChildren =
  {
    ChatConversationsIdRoute: ChatConversationsIdRoute,
    ChatConversationsIndexRoute: ChatConversationsIndexRoute,
  }

const ChatConversationsRouteRouteWithChildren =
  ChatConversationsRouteRoute._addFileChildren(
    ChatConversationsRouteRouteChildren,
  )

interface ChatRouteRouteChildren {
  ChatConversationsRouteRoute: typeof ChatConversationsRouteRouteWithChildren
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatConversationsRouteRoute: ChatConversationsRouteRouteWithChildren,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

interface GatewayRouteRouteChildren {
  GatewayEvalsRoute: typeof GatewayEvalsRoute
  GatewayGuardrailsRoute: typeof GatewayGuardrailsRoute
  GatewayModelsRoute: typeof GatewayModelsRoute
  GatewayOverviewRoute: typeof GatewayOverviewRoute
  GatewayPlaygroundRoute: typeof GatewayPlaygroundRoute
  GatewayProvidersRoute: typeof GatewayProvidersRoute
  GatewayRoutingRoute: typeof GatewayRoutingRoute
  GatewaySnippetsRoute: typeof GatewaySnippetsRoute
  GatewayTracesRoute: typeof GatewayTracesRoute
  GatewayIndexRoute: typeof GatewayIndexRoute
}

const GatewayRouteRouteChildren: GatewayRouteRouteChildren = {
  GatewayEvalsRoute: GatewayEvalsRoute,
  GatewayGuardrailsRoute: GatewayGuardrailsRoute,
  GatewayModelsRoute: GatewayModelsRoute,
  GatewayOverviewRoute: GatewayOverviewRoute,
  GatewayPlaygroundRoute: GatewayPlaygroundRoute,
  GatewayProvidersRoute: GatewayProvidersRoute,
  GatewayRoutingRoute: GatewayRoutingRoute,
  GatewaySnippetsRoute: GatewaySnippetsRoute,
  GatewayTracesRoute: GatewayTracesRoute,
  GatewayIndexRoute: GatewayIndexRoute,
}

const GatewayRouteRouteWithChildren = GatewayRouteRoute._addFileChildren(
  GatewayRouteRouteChildren,
)

interface RagRouteRouteChildren {
  RagMarketplaceRoute: typeof RagMarketplaceRoute
  RagSearchProvidersRoute: typeof RagSearchProvidersRoute
  RagKbsIndexRoute: typeof RagKbsIndexRoute
  RagKbsIdAnalyticsRoute: typeof RagKbsIdAnalyticsRoute
  RagKbsIdConnectorsRoute: typeof RagKbsIdConnectorsRoute
  RagKbsIdDocumentsRoute: typeof RagKbsIdDocumentsRoute
  RagKbsIdEvalsRoute: typeof RagKbsIdEvalsRoute
  RagKbsIdOverviewRoute: typeof RagKbsIdOverviewRoute
  RagKbsIdPermissionsRoute: typeof RagKbsIdPermissionsRoute
  RagKbsIdPlaygroundRoute: typeof RagKbsIdPlaygroundRoute
  RagKbsIdQuarantineRoute: typeof RagKbsIdQuarantineRoute
  RagKbsIdSettingsRoute: typeof RagKbsIdSettingsRoute
}

const RagRouteRouteChildren: RagRouteRouteChildren = {
  RagMarketplaceRoute: RagMarketplaceRoute,
  RagSearchProvidersRoute: RagSearchProvidersRoute,
  RagKbsIndexRoute: RagKbsIndexRoute,
  RagKbsIdAnalyticsRoute: RagKbsIdAnalyticsRoute,
  RagKbsIdConnectorsRoute: RagKbsIdConnectorsRoute,
  RagKbsIdDocumentsRoute: RagKbsIdDocumentsRoute,
  RagKbsIdEvalsRoute: RagKbsIdEvalsRoute,
  RagKbsIdOverviewRoute: RagKbsIdOverviewRoute,
  RagKbsIdPermissionsRoute: RagKbsIdPermissionsRoute,
  RagKbsIdPlaygroundRoute: RagKbsIdPlaygroundRoute,
  RagKbsIdQuarantineRoute: RagKbsIdQuarantineRoute,
  RagKbsIdSettingsRoute: RagKbsIdSettingsRoute,
}

const RagRouteRouteWithChildren = RagRouteRoute._addFileChildren(
  RagRouteRouteChildren,
)

interface WorkersInstancesRouteChildren {
  WorkersInstancesWorkerIdRoute: typeof WorkersInstancesWorkerIdRoute
}

const WorkersInstancesRouteChildren: WorkersInstancesRouteChildren = {
  WorkersInstancesWorkerIdRoute: WorkersInstancesWorkerIdRoute,
}

const WorkersInstancesRouteWithChildren =
  WorkersInstancesRoute._addFileChildren(WorkersInstancesRouteChildren)

interface WorkersPoolsRouteChildren {
  WorkersPoolsIdTemplateRoute: typeof WorkersPoolsIdTemplateRoute
}

const WorkersPoolsRouteChildren: WorkersPoolsRouteChildren = {
  WorkersPoolsIdTemplateRoute: WorkersPoolsIdTemplateRoute,
}

const WorkersPoolsRouteWithChildren = WorkersPoolsRoute._addFileChildren(
  WorkersPoolsRouteChildren,
)

interface WorkersTasksRouteChildren {
  WorkersTasksTaskIdRoute: typeof WorkersTasksTaskIdRoute
}

const WorkersTasksRouteChildren: WorkersTasksRouteChildren = {
  WorkersTasksTaskIdRoute: WorkersTasksTaskIdRoute,
}

const WorkersTasksRouteWithChildren = WorkersTasksRoute._addFileChildren(
  WorkersTasksRouteChildren,
)

interface WorkersRouteRouteChildren {
  WorkersAnalyticsRoute: typeof WorkersAnalyticsRoute
  WorkersInstancesRoute: typeof WorkersInstancesRouteWithChildren
  WorkersIntegrationsRoute: typeof WorkersIntegrationsRoute
  WorkersPoolsRoute: typeof WorkersPoolsRouteWithChildren
  WorkersSettingsRoute: typeof WorkersSettingsRoute
  WorkersTasksRoute: typeof WorkersTasksRouteWithChildren
  WorkersIndexRoute: typeof WorkersIndexRoute
}

const WorkersRouteRouteChildren: WorkersRouteRouteChildren = {
  WorkersAnalyticsRoute: WorkersAnalyticsRoute,
  WorkersInstancesRoute: WorkersInstancesRouteWithChildren,
  WorkersIntegrationsRoute: WorkersIntegrationsRoute,
  WorkersPoolsRoute: WorkersPoolsRouteWithChildren,
  WorkersSettingsRoute: WorkersSettingsRoute,
  WorkersTasksRoute: WorkersTasksRouteWithChildren,
  WorkersIndexRoute: WorkersIndexRoute,
}

const WorkersRouteRouteWithChildren = WorkersRouteRoute._addFileChildren(
  WorkersRouteRouteChildren,
)

interface MemoriesRouteChildren {
  MemoriesMyRoute: typeof MemoriesMyRoute
  MemoriesSettingsRoute: typeof MemoriesSettingsRoute
  MemoriesSharedRoute: typeof MemoriesSharedRoute
}

const MemoriesRouteChildren: MemoriesRouteChildren = {
  MemoriesMyRoute: MemoriesMyRoute,
  MemoriesSettingsRoute: MemoriesSettingsRoute,
  MemoriesSharedRoute: MemoriesSharedRoute,
}

const MemoriesRouteWithChildren = MemoriesRoute._addFileChildren(
  MemoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ChatRouteRoute: ChatRouteRouteWithChildren,
  GatewayRouteRoute: GatewayRouteRouteWithChildren,
  RagRouteRoute: RagRouteRouteWithChildren,
  WorkersRouteRoute: WorkersRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  MemoriesRoute: MemoriesRouteWithChildren,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
  KnowledgeBasesIdRoute: KnowledgeBasesIdRoute,
  OrgConsumptionRoute: OrgConsumptionRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  KnowledgeBasesIndexRoute: KnowledgeBasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
