/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteRouteImport } from './routes/chat/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeBasesIndexRouteImport } from './routes/knowledge-bases/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrgSettingsRouteImport } from './routes/org/settings'
import { Route as OrgConsumptionRouteImport } from './routes/org/consumption'
import { Route as KnowledgeBasesIdRouteImport } from './routes/knowledge-bases/$id'
import { Route as AdminSsoRouteImport } from './routes/admin/sso'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminApiKeysRouteImport } from './routes/admin/api-keys'
import { Route as ChatConversationsRouteRouteImport } from './routes/chat/conversations/route'
import { Route as ChatConversationsIndexRouteImport } from './routes/chat/conversations/index'
import { Route as ChatConversationsIdRouteImport } from './routes/chat/conversations/$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBasesIndexRoute = KnowledgeBasesIndexRouteImport.update({
  id: '/knowledge-bases/',
  path: '/knowledge-bases/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/org/settings',
  path: '/org/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgConsumptionRoute = OrgConsumptionRouteImport.update({
  id: '/org/consumption',
  path: '/org/consumption',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBasesIdRoute = KnowledgeBasesIdRouteImport.update({
  id: '/knowledge-bases/$id',
  path: '/knowledge-bases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSsoRoute = AdminSsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ChatConversationsRouteRoute = ChatConversationsRouteRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ChatConversationsIndexRoute = ChatConversationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatConversationsRouteRoute,
} as any)
const ChatConversationsIdRoute = ChatConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatConversationsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/chat': typeof ChatRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/chat/conversations': typeof ChatConversationsRouteRouteWithChildren
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/sso': typeof AdminSsoRoute
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
  '/org/consumption': typeof OrgConsumptionRoute
  '/org/settings': typeof OrgSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/knowledge-bases/': typeof KnowledgeBasesIndexRoute
  '/chat/conversations/$id': typeof ChatConversationsIdRoute
  '/chat/conversations/': typeof ChatConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/sso': typeof AdminSsoRoute
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
  '/org/consumption': typeof OrgConsumptionRoute
  '/org/settings': typeof OrgSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/knowledge-bases': typeof KnowledgeBasesIndexRoute
  '/chat/conversations/$id': typeof ChatConversationsIdRoute
  '/chat/conversations': typeof ChatConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/chat': typeof ChatRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/chat/conversations': typeof ChatConversationsRouteRouteWithChildren
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/sso': typeof AdminSsoRoute
  '/knowledge-bases/$id': typeof KnowledgeBasesIdRoute
  '/org/consumption': typeof OrgConsumptionRoute
  '/org/settings': typeof OrgSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/knowledge-bases/': typeof KnowledgeBasesIndexRoute
  '/chat/conversations/$id': typeof ChatConversationsIdRoute
  '/chat/conversations/': typeof ChatConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/login'
    | '/memories'
    | '/register'
    | '/setup'
    | '/chat/conversations'
    | '/admin/api-keys'
    | '/admin/members'
    | '/admin/sso'
    | '/knowledge-bases/$id'
    | '/org/consumption'
    | '/org/settings'
    | '/admin/'
    | '/knowledge-bases/'
    | '/chat/conversations/$id'
    | '/chat/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/memories'
    | '/register'
    | '/setup'
    | '/admin/api-keys'
    | '/admin/members'
    | '/admin/sso'
    | '/knowledge-bases/$id'
    | '/org/consumption'
    | '/org/settings'
    | '/admin'
    | '/knowledge-bases'
    | '/chat/conversations/$id'
    | '/chat/conversations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/login'
    | '/memories'
    | '/register'
    | '/setup'
    | '/chat/conversations'
    | '/admin/api-keys'
    | '/admin/members'
    | '/admin/sso'
    | '/knowledge-bases/$id'
    | '/org/consumption'
    | '/org/settings'
    | '/admin/'
    | '/knowledge-bases/'
    | '/chat/conversations/$id'
    | '/chat/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  MemoriesRoute: typeof MemoriesRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
  KnowledgeBasesIdRoute: typeof KnowledgeBasesIdRoute
  OrgConsumptionRoute: typeof OrgConsumptionRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  KnowledgeBasesIndexRoute: typeof KnowledgeBasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-bases/': {
      id: '/knowledge-bases/'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases/'
      preLoaderRoute: typeof KnowledgeBasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/org/settings': {
      id: '/org/settings'
      path: '/org/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/consumption': {
      id: '/org/consumption'
      path: '/org/consumption'
      fullPath: '/org/consumption'
      preLoaderRoute: typeof OrgConsumptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-bases/$id': {
      id: '/knowledge-bases/$id'
      path: '/knowledge-bases/$id'
      fullPath: '/knowledge-bases/$id'
      preLoaderRoute: typeof KnowledgeBasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sso': {
      id: '/admin/sso'
      path: '/sso'
      fullPath: '/admin/sso'
      preLoaderRoute: typeof AdminSsoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/chat/conversations': {
      id: '/chat/conversations'
      path: '/conversations'
      fullPath: '/chat/conversations'
      preLoaderRoute: typeof ChatConversationsRouteRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/chat/conversations/': {
      id: '/chat/conversations/'
      path: '/'
      fullPath: '/chat/conversations/'
      preLoaderRoute: typeof ChatConversationsIndexRouteImport
      parentRoute: typeof ChatConversationsRouteRoute
    }
    '/chat/conversations/$id': {
      id: '/chat/conversations/$id'
      path: '/$id'
      fullPath: '/chat/conversations/$id'
      preLoaderRoute: typeof ChatConversationsIdRouteImport
      parentRoute: typeof ChatConversationsRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminSsoRoute: typeof AdminSsoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminSsoRoute: AdminSsoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ChatConversationsRouteRouteChildren {
  ChatConversationsIdRoute: typeof ChatConversationsIdRoute
  ChatConversationsIndexRoute: typeof ChatConversationsIndexRoute
}

const ChatConversationsRouteRouteChildren: ChatConversationsRouteRouteChildren =
  {
    ChatConversationsIdRoute: ChatConversationsIdRoute,
    ChatConversationsIndexRoute: ChatConversationsIndexRoute,
  }

const ChatConversationsRouteRouteWithChildren =
  ChatConversationsRouteRoute._addFileChildren(
    ChatConversationsRouteRouteChildren,
  )

interface ChatRouteRouteChildren {
  ChatConversationsRouteRoute: typeof ChatConversationsRouteRouteWithChildren
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatConversationsRouteRoute: ChatConversationsRouteRouteWithChildren,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ChatRouteRoute: ChatRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  MemoriesRoute: MemoriesRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
  KnowledgeBasesIdRoute: KnowledgeBasesIdRoute,
  OrgConsumptionRoute: OrgConsumptionRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  KnowledgeBasesIndexRoute: KnowledgeBasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
