"""Tests for the per-pool PR template formatter."""

from __future__ import annotations

import httpx
import pytest
import respx

from ai_portal.workers.git.protocol import RepoRef
from ai_portal.workers.git.pr_templates import (
    PrTemplate,
    apply_template,
)
from ai_portal.workers.git.providers.github import GitHubProvider
from ai_portal.workers.git.providers.gitlab import GitLabProvider


REPO = RepoRef("acme/api", "main", "https://github.com/acme/api.git")


# ---------------- pure formatter ----------------


def test_apply_template_default_when_none() -> None:
    out = apply_template(
        None,
        title="fix bug",
        body="raw body",
        task_id="t-1",
        branch="worker/t-1",
        repo="acme/api",
        summary="raw body",
    )
    assert out["title"] == "fix bug"
    assert out["body"] == "raw body"


def test_apply_template_interpolates_title_and_body() -> None:
    tpl: PrTemplate = {
        "title_format": "[Bot] {title} ({task_id})",
        "description_format": "Task: {task_id}\nRepo: {repo}\nBranch: {branch}\n\n{summary}",
        "test_plan": "- run pytest\n- run lint",
        "generated_by_tag": "Generated by ai-portal-worker",
    }
    out = apply_template(
        tpl,
        title="fix bug",
        body="ignored",
        task_id="t-1",
        branch="worker/t-1",
        repo="acme/api",
        summary="fixed the parser",
    )
    assert out["title"] == "[Bot] fix bug (t-1)"
    assert "Task: t-1" in out["body"]
    assert "Branch: worker/t-1" in out["body"]
    assert "fixed the parser" in out["body"]
    assert "## Test Plan" in out["body"]
    assert "- run pytest" in out["body"]
    assert "Generated by ai-portal-worker" in out["body"]


def test_apply_template_missing_keys_kept_literal() -> None:
    tpl: PrTemplate = {
        "title_format": "{title} [{unknown_key}]",
        "description_format": "{summary}",
    }
    out = apply_template(
        tpl,
        title="t",
        body="b",
        task_id="x",
        branch="x",
        repo="x",
        summary="s",
    )
    # unknown keys preserved as literal {unknown_key}
    assert "{unknown_key}" in out["title"]


# ---------------- github provider honors template ----------------


def _pr_body(number: int = 7) -> dict:
    return {
        "id": 1,
        "number": number,
        "html_url": f"https://github.com/acme/api/pull/{number}",
        "state": "open",
        "draft": True,
        "head": {"ref": "worker/t-1"},
        "base": {"ref": "main"},
        "title": "ignored",
        "body": "ignored",
    }


@pytest.mark.asyncio
async def test_github_create_pr_uses_template() -> None:
    tpl: PrTemplate = {
        "title_format": "[AI] {title}",
        "description_format": "T={task_id}\n\n{summary}",
        "test_plan": "- pytest",
        "generated_by_tag": "ai-portal",
    }
    captured: dict = {}

    def _capture(request: httpx.Request) -> httpx.Response:
        captured["json"] = request.read().decode()
        return httpx.Response(201, json=_pr_body())

    async with respx.mock(assert_all_called=True) as mock:
        mock.post(
            "https://api.github.com/repos/acme/api/pulls"
        ).mock(side_effect=_capture)
        p = GitHubProvider(token="ghs_fake")
        await p.create_pr(
            REPO,
            head="worker/t-1",
            base="main",
            title="fix",
            body="raw",
            draft=True,
            template=tpl,
            task_id="t-99",
            summary="did the thing",
        )
    body = captured["json"]
    assert '"title":"[AI] fix"' in body or '"title": "[AI] fix"' in body
    assert "T=t-99" in body
    assert "did the thing" in body
    assert "- pytest" in body
    assert "ai-portal" in body


@pytest.mark.asyncio
async def test_gitlab_create_pr_uses_template() -> None:
    tpl: PrTemplate = {
        "title_format": "[AI] {title}",
        "description_format": "T={task_id}\nB={branch}\n\n{summary}",
    }
    captured: dict = {}

    def _capture(request: httpx.Request) -> httpx.Response:
        captured["json"] = request.read().decode()
        return httpx.Response(
            201,
            json={
                "id": 1,
                "iid": 42,
                "web_url": "https://gitlab.com/acme/api/-/merge_requests/42",
                "state": "opened",
                "source_branch": "worker/t-1",
                "target_branch": "main",
                "title": "x",
                "description": "x",
                "draft": True,
            },
        )

    async with respx.mock(assert_all_called=True) as mock:
        mock.post(
            "https://gitlab.com/api/v4/projects/acme%2Fapi/merge_requests"
        ).mock(side_effect=_capture)
        p = GitLabProvider(token="glpat_fake")
        await p.create_pr(
            REPO,
            head="worker/t-1",
            base="main",
            title="fix",
            body="raw",
            draft=False,
            template=tpl,
            task_id="t-50",
            summary="hello",
        )
    body = captured["json"]
    assert '"title":"[AI] fix"' in body or '"title": "[AI] fix"' in body
    assert "T=t-50" in body
    assert "B=worker/t-1" in body
